dependencies:
  - biopython
  - fastp
  - gzip
  - imagemagick
  - numpy
  - matplotlib
  - megahit
  - minimap2
  - samtools
  - scikit-learn
  - seaborn
  - seqkit
  - snakemake
  - spades
  - pandas
  - prodigal
  - python=3.11
